name: day_night_switcher
description: A simple day / night switcher widget made in pure Dart. Allows to quickly show a beautiful dark mode switcher widget to your users.
version: 0.1.1+1
homepage: https://github.com/Skyost/DayNightSwitcher

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
