name: day_night_switcher
description: A simple day / night switcher widget made in pure Dart.
version: 0.1.0
homepage: https://github.com/Skyost/DayNightSwitcher

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

